### ISSUE TITLE
Constant idle cpu load

### ISSUE THREAD

**Issue by ValdikSS** [itemir/thundersec#17] opened 2015-05-09 21:52 UTC
ThunderSec 1.0.2 is constantly loads cpu even if nothing happens.

**Comment by itemir** [comment] 2015-05-09 23:33
Thanks for the report. Obviously, this should not happen. 

Can you provide some more details? What OS and what version of TB are you using? How do you measure the CPU?

**Comment by ValdikSS** [comment] 2015-05-10 09:17
I'm using Thunderbird 31.6.0 on ArchLinux. ThunderSec 1.0.2 is from Mozilla addons repository.
If ThunderSec is enabled, Thunderbird constantly consumes 7-8% of CPU. With ThunderSec disabled, the load is at usual 0-1%. Load is monitored with htop.

**Comment by itemir** [comment] 2015-05-11 17:48
Thanks. We will look into this.

**Comment by itemir** [comment] 2015-05-12 00:13
Initial troubleshooting seems to indicate this is coming from jquery code. jquery library is used within Thundersec for simplifying some of the operations. Unfortunately we have no control over the jquery code itself. 

I will do more troubleshooting and if this is confirmed, we may need to remove jquery and replicate the needed functionality in native code. Unfortunately this will require quite some work.

**Comment by itemir** [comment] 2015-05-12 07:21
Looks like it is the backwards compatible code in jquery for IE 6, 7 and 8 was causing the issue. jquery 2.x drops support for those. Changing the jquery library from 1.11.2 to 2.1.4 fixed the issue. 

Please test and re-open if necessary.

**Comment by ValdikSS** [comment] 2015-05-12 07:26
Thank you! That works.

**Comment by ValdikSS** [comment] 2015-05-12 07:32
This fix broke ThunderSec dialog window. There is no text now.

**Comment by itemir** [comment] 2015-05-12 19:44
I overlooked it, one should not commit code past midnight. Please try again.

**Comment by ValdikSS** [comment] 2015-05-12 19:47
All fine, thanks a lot!

**Comment by itemir** [comment] 2015-05-12 20:33
No problem. If you like using the plugin, please consider writing a review. We would like to get as much feedback as possible.

**Comment by ValdikSS** [comment] 2016-01-13 11:18
Hi!
After updating to 2.0 version the issue returned.

**Comment by itemir** [comment] 2016-01-13 21:47
Thanks, will look at it.

**Comment by itemir** [comment] 2016-01-14 00:09
I don't see this behavior on my machine running Thunderbird on OS X. I am watching the Thunderbird process but when it goes idle, it goes down to 0% and stays there. Can you please confirm the test in a more isolated manner? 

Also is there anyone else seeing the same behavior?

**Comment by ValdikSS** [comment] 2016-01-14 06:46
When I open any email, it tries to resolve DNS ("Number of outstanding DNS lookups") and never succeeds. And probably a spinning animation is what consumes CPU.

**Comment by t1msammut** [comment] 2016-01-14 16:27
I am not seeing that behavior with Thunderbird 38.5.0 on Linux.

**Comment by itemir** [comment] 2016-01-14 16:30
Valdik. I don't see it either. Can you try to disable the SURBL services (uncheck them in Preferences) and see what happens?

**Comment by ValdikSS** [comment] 2016-01-14 19:47
Disabling SURBL helps. This happens for me only on mails from habrahabr.ru.

**Comment by itemir** [comment] 2016-01-15 00:03
Sounds like it is some link in the mail body that is causing parsing problems. We need to look into that. However it is a very different issue than what was reported/addressed in this ticket. 

I opened issue #24 for it. I will close this ticket, let's keep troubleshooting it there.

**Closed by itemir** 2016-01-15 00:03 UTC
Labels: bug
